server {
    listen 8080;
    server_name localhost;
    host 127.0.0.1;
    
    root ./www; 
    
    client_max_body_size 10M;

    # error_page 400 /errors/400.html;
    # error_page 401 /errors/401.html;
    # error_page 403 /errors/403.html;
    # error_page 404 /errors/404.html;
    # error_page 405 /errors/405.html;
    # error_page 500 /errors/500.html;
    # error_page 501 /errors/501.html;

    location / {
        root ./www;
        allow_methods GET POST;
        index index.html;
    }

    location /static {
        allow_methods GET POST;
        autoindex off;
    }

    location /upload {
        allow_methods GET POST;
        index index.html;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        autoindex on;
        upload_enabled on;
    }

    location /delete {
        allow_methods GET DELETE;
        index index.html;
    }

    location /submit {
        allow_methods GET POST;
        index index.html;
    }

    location /redirect {
        return 301 /submit/;
    }

    location /dont-have-access {
        allow_methods POST;
    }

    location /private {
        root ./www/private;
        allow_methods GET POST;
        auth_required on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        index index.html;
        cgi_ext .py; 
        cgi_path /usr/bin/python3;
    }
}