name: CI Check

on:
  push:
    branches:
      - main
      - develop
      - prod
      - feature/improving_main 
  pull_request:
    branches:
      - main
      - develop
      - prod

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up C environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind clang-format clang-tidy cppcheck libclang-18-dev python3-clang-18 siege

    # Compilation check
    - name: Compile Project
      run: make re

    # Check if its runinig and have valid response
    # - name: Run ALL Test
    #   run: |
    #     ./tests/scripts/start_all.sh

    # Check if its runinig and have valid response
    - name: Run CGI Test
      run: |
        ./tests/scripts/test_cgi.sh
    
    - name: Run Response Test
      run: |
        ./tests/scripts/test_response.sh
        
    # Check how it performs under load, expects min 95% success rate
    - name: Run Load Test for 10 seconds
      run: |
        ./tests/scripts/test_load.sh

    # Check for memory leaks with valgrind
    - name: Run Valgrind Test
      run: |
        ./tests/scripts/test_memory.sh

    # Check load on 10 ports for 5 seconds each
    - name: Run Multi ports Load Test for 5 seconds each
      run: |
        ./tests/scripts/test_multi_ports_load.sh
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
    steps:
      - name: Trigger CD Deployment on Render
        run: curl -X POST "${{ secrets.DEPLOY_HOOK }}"
